apiVersion: v1
data:
  conf.ini: |
    [System]
    ; 运行模式
    Mode = master
    ; 监听端口
    ; Listen = :5000
    ; 是否开启 Debug
    Debug = true
    ; Session 密钥, 一般在首次启动时自动生成
    ; SessionSecret = 23333
    ; Hash 加盐, 一般在首次启动时自动生成
    ; HashIDSalt = something really hard to guss
    ;
    ; 数据库相关，如果你只想使用内置的 SQLite数据库，这一部分直接删去即可
    [Database]
    ; 数据库类型，目前支持 sqlite | mysql
    Type = mysql
    ; MySQL 端口
    Port = 53306
    ; 用户名
    User = root
    ; 密码
    Password = xxxxxxxx.org.xxx
    ; 数据库地址
    Host = 192.168.0.114
    ; 数据库名称
    Name = v3
    ; 数据表前缀
    TablePrefix = cd
    ; ; SQLite 数据库文件路径
    ; DBFile = cloudreve.db
    ;
    ; 跨域配置
    [CORS]
    AllowOrigins = *
    AllowMethods = OPTIONS,GET,POST
    AllowHeaders = *
    AllowCredentials = false

    ; Redis 相关
    [Redis]
    Server = 192.168.0.114:6379
    Password = "passwdxxx"
    DB = 3
kind: ConfigMap
metadata:
  name: cloudreveconf
  namespace: mlab2

---
apiVersion: v1
kind: Pod
metadata:
  name: cloudreve
  namespace: mlab2
  labels:
    app: cloudreve
spec:
  nodeName: ai05
  containers:
  - name: cloudreve 
    image: gemfield/cloudreve:3.3.1
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    env:
    - name: TZ 
      value: Asia/Shanghai
    ports:
    - name: upload
      containerPort: 5212
    volumeMounts:
    - name: mlab2up
      mountPath: /cloudreve/uploads/
      subPath: airlock
    - name: cloudconf
      mountPath: /cloudreve/conf.ini
      subPath: conf.ini
  hostNetwork: false
  restartPolicy: Always 
  volumes:
  - name: cloudconf
    configMap:
      name: cloudreveconf
  - name: mlab2up
    persistentVolumeClaim:
       claimName: public-dataset
---
apiVersion: v1
kind: Service
metadata:
  name: cloudreve-service
  namespace: mlab2
  labels:
    app: cloudreve
spec:
  externalIPs:
    - 192.168.0.168
  ports:
    - port: 5212
      targetPort: 5212
      name: upload
  selector:
    app: cloudreve
